// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Morpheus.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Morpheus.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20260705185902_FeedSubscriptions")]
    partial class FeedSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Morpheus.Database.Models.BotSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("BotSettings");
                });

            modelBuilder.Entity("Morpheus.Database.Models.ButtonGamePress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GuildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Score")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InsertDate");

                    b.HasIndex("GuildId", "InsertDate");

                    b.HasIndex("UserId", "InsertDate");

                    b.ToTable("ButtonGamePresses");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("HoneypotChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LevelUpMessages")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LevelUpMessagesChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("LevelUpQuotes")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LevelUpQuotesChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PinsChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuoteAddRequiredApprovals")
                        .HasColumnType("integer");

                    b.Property<int>("QuoteRemoveRequiredApprovals")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuotesApprovalChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("SendHoneypotMessages")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseActivityRoles")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseGlobalQuotes")
                        .HasColumnType("boolean");

                    b.Property<decimal>("WelcomeChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("WelcomeMessages")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InsertDate", "Severity");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.HasIndex("InsertDate", "Approved", "Removed");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("Morpheus.Database.Models.QuoteApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuoteApprovalMessageId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteApprovalMessageId", "UserId")
                        .IsUnique();

                    b.ToTable("QuoteApprovals");
                });

            modelBuilder.Entity("Morpheus.Database.Models.QuoteApprovalMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ApprovalMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.HasIndex("Approved", "InsertDate");

                    b.ToTable("QuoteApprovalMessages");
                });

            modelBuilder.Entity("Morpheus.Database.Models.QuoteScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuoteId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("QuoteId", "UserId")
                        .IsUnique();

                    b.ToTable("QuoteScores");
                });

            modelBuilder.Entity("Morpheus.Database.Models.ReactionRoleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReactionRoleMessageId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ReactionRoleMessageId", "Emoji")
                        .IsUnique();

                    b.HasIndex("ReactionRoleMessageId", "RoleId")
                        .IsUnique();

                    b.ToTable("ReactionRoleItems");
                });

            modelBuilder.Entity("Morpheus.Database.Models.ReactionRoleMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("UseButtons")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("ReactionRoleMessages");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GuildId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("RoleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyChangePercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PreviousPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UpdateTimeMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId")
                        .IsUnique();

                    b.HasIndex("LastUpdatedDate", "UpdateTimeMinutes");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Morpheus.Database.Models.StockHolding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Shares")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalInvested")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId", "StockId")
                        .IsUnique();

                    b.ToTable("StockHoldings");
                });

            modelBuilder.Entity("Morpheus.Database.Models.StockTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PriceAtTransaction")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Shares")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("StockId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InsertDate");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("StockId", "InsertDate");

                    b.HasIndex("UserId", "InsertDate");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("Morpheus.Database.Models.TemporaryBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UnbannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt", "UnbannedAt");

                    b.HasIndex("GuildId", "UserId");

                    b.ToTable("TemporaryBans");
                });

            modelBuilder.Entity("Morpheus.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(1000.00m);

                    b.Property<decimal>("DiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastRobberyAttempt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSuccessfullyRobbed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUsernameCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LevelUpMessages")
                        .HasColumnType("boolean");

                    b.Property<bool>("LevelUpQuotes")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Morpheus.Database.Models.UserActivity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("DiscordMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<double>("GuildAverageMessageLength")
                        .HasColumnType("double precision");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<int>("GuildMessageCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageLength")
                        .HasColumnType("integer");

                    b.Property<decimal>("MessageSimHash")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("NormalizedLength")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("XpGained")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InsertDate");

                    b.HasIndex("DiscordChannelId", "InsertDate");

                    b.HasIndex("GuildId", "InsertDate");

                    b.HasIndex("InsertDate", "DiscordChannelId");

                    b.HasIndex("InsertDate", "GuildId");

                    b.HasIndex("InsertDate", "UserId");

                    b.HasIndex("UserId", "GuildId", "InsertDate");

                    b.ToTable("UserActivity");
                });

            modelBuilder.Entity("Morpheus.Database.Models.UserLevels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer");

                    b.Property<double>("UserAverageMessageLength")
                        .HasColumnType("double precision");

                    b.Property<double>("UserAverageMessageLengthEma")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("UserMessageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("UserId", "GuildId")
                        .IsUnique();

                    b.ToTable("UserLevels");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Webhook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelDiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildDiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WebhookId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelDiscordId")
                        .IsUnique();

                    b.ToTable("Webhooks");
                });

            modelBuilder.Entity("Morpheus.Database.Models.XkcdSeen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.ToTable("XkcdSeen");
                });

            modelBuilder.Entity("Morpheus.Database.Models.XkcdSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelDiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildDiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WebhookId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChannelDiscordId")
                        .IsUnique();

                    b.HasIndex("WebhookId");

                    b.ToTable("XkcdSubscriptions");
                });

            modelBuilder.Entity("Morpheus.Database.Models.YoutubeSeenVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YoutubeChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("YoutubeSeenVideos");
                });

            modelBuilder.Entity("Morpheus.Database.Models.YoutubeSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelDiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildDiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WebhookId")
                        .HasColumnType("integer");

                    b.Property<string>("YoutubeAvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("YoutubeChannelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YoutubeChannelTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("WebhookId");

                    b.HasIndex("YoutubeChannelId");

                    b.HasIndex("ChannelDiscordId", "YoutubeChannelId")
                        .IsUnique();

                    b.ToTable("YoutubeSubscriptions");
                });

            modelBuilder.Entity("Morpheus.Database.Models.ButtonGamePress", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Guild", "Guild")
                        .WithMany("ButtonGamePresses")
                        .HasForeignKey("GuildId");

                    b.HasOne("Morpheus.Database.Models.User", "User")
                        .WithMany("ButtonGamePresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Quote", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Guild", "Guild")
                        .WithMany("Quotes")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Morpheus.Database.Models.User", "User")
                        .WithMany("Quotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Morpheus.Database.Models.QuoteApproval", b =>
                {
                    b.HasOne("Morpheus.Database.Models.QuoteApprovalMessage", "ApprovalMessage")
                        .WithMany()
                        .HasForeignKey("QuoteApprovalMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalMessage");
                });

            modelBuilder.Entity("Morpheus.Database.Models.QuoteApprovalMessage", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("Morpheus.Database.Models.QuoteScore", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Quote", "Quote")
                        .WithMany("Scores")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Morpheus.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Morpheus.Database.Models.ReactionRoleItem", b =>
                {
                    b.HasOne("Morpheus.Database.Models.ReactionRoleMessage", "ReactionRoleMessage")
                        .WithMany("Items")
                        .HasForeignKey("ReactionRoleMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReactionRoleMessage");
                });

            modelBuilder.Entity("Morpheus.Database.Models.ReactionRoleMessage", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Reminder", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Guild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId");

                    b.HasOne("Morpheus.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Role", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Guild", "Guild")
                        .WithMany("Roles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Morpheus.Database.Models.StockHolding", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Stock", "Stock")
                        .WithMany("StockHoldings")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Morpheus.Database.Models.User", "User")
                        .WithMany("StockHoldings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Morpheus.Database.Models.StockTransaction", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId");

                    b.HasOne("Morpheus.Database.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Morpheus.Database.Models.User", "User")
                        .WithMany("StockTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Morpheus.Database.Models.UserActivity", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Guild", "Guild")
                        .WithMany("UserActivity")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Morpheus.Database.Models.User", "User")
                        .WithMany("UserActivity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Morpheus.Database.Models.UserLevels", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Guild", "Guild")
                        .WithMany("UserLevels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Morpheus.Database.Models.User", "User")
                        .WithMany("UserLevels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Morpheus.Database.Models.XkcdSubscription", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Webhook", "Webhook")
                        .WithMany()
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("Morpheus.Database.Models.YoutubeSubscription", b =>
                {
                    b.HasOne("Morpheus.Database.Models.Webhook", "Webhook")
                        .WithMany()
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Guild", b =>
                {
                    b.Navigation("ButtonGamePresses");

                    b.Navigation("Quotes");

                    b.Navigation("Roles");

                    b.Navigation("UserActivity");

                    b.Navigation("UserLevels");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Quote", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("Morpheus.Database.Models.ReactionRoleMessage", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Morpheus.Database.Models.Stock", b =>
                {
                    b.Navigation("StockHoldings");
                });

            modelBuilder.Entity("Morpheus.Database.Models.User", b =>
                {
                    b.Navigation("ButtonGamePresses");

                    b.Navigation("Quotes");

                    b.Navigation("StockHoldings");

                    b.Navigation("StockTransactions");

                    b.Navigation("UserActivity");

                    b.Navigation("UserLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
